### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by dmitzsaz** [szastupov/musicbot#4]
INFO:rest:serving REST on ('0.0.0.0', 8080)
WARNING:aiohttp.client:Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    loop.run_until_complete(start())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "main.py", line 13, in start
    await bot.loop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiotg/bot.py", line 215, in loop
    timeout=self.api_timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiotg/bot.py", line 65, in api_call
    return (yield from response.json())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 745, in json
    return loads(stripped.decode(encoding))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by szastupov** [comment]
It's hard to tell, perhaps you provided a wrong API key? Could you put a few print() into aiotg bot.py code to see what is wrong?

**Comment by dmitzsaz** [comment]
I can send example-compose.yml

**Comment by dmitzsaz** [comment]
I'm Russia

**Comment by dmitzsaz** [comment]
Привет

**Comment by dmitzsaz** [comment]
Where this API Key?

**Comment by szastupov** [comment]
Ты как запускаешь бота? Скинь параметры.

**Comment by dmitzsaz** [comment]
Просто python3 main.py

**Comment by superdima05** [comment]
Ауу

**Comment by dmitzsaz** [comment]
Вот файл example-compose.yml:

**Comment by dmitzsaz** [comment]
musicbot:
  image: szastupov/musicbot
  restart: always
  links:
    - mongo
  environment:
    - BOT_NAME=DimaMusic
    - API_TOKEN=143804876:AAEvMv0v5NwClPfBQgQN_057bDFEvPZD3aU
    - BOTAN_TOKEN=Optional botan token
    - MONGO_HOST=mongo
mongo:
  image: mongo
  restart: always

**Comment by szastupov** [comment]
Блин, чувак, не хочу показаться грубым но все же написано в инструкциях. Если руками запускаешь то передай через enviorment.
Почитай про Bot API https://core.telegram.org/api
Потом перечитай README.md бота, до полного просветления :)

**Comment by dmitzsaz** [comment]
OK

**Comment by dmitzsaz** [comment]
Но в ошибках написано про ошибки в папке Python

**Comment by dmitzsaz** [comment]
Ошибка в настройках?

**Comment by dmitzsaz** [comment]
Спасибо большое! Всё заработало надо было добавить одну комманду к боту

**Comment by szastupov** [comment]
👍
